version: '3.9'

services:
  database:
    image: "postgres:15"
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '1433:5432'
    container_name: "database"

  backend:
    image: application
    restart: always
    build:
      context: ../
      dockerfile: Presentation\TechRental.Presentation.WebAPI\Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: server

  frontend:
    container_name: client
    build:
      context: ../../client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  
  proxy:
    container_name: nginx
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:8080'